development:
  adapter: postgresql
  database: testblog_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: testblog_test
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: testblog_production
  pool: 5
  timeout: 5000